FROM weef/php:7.1-fpm

USER root

RUN mkdir -p /var/www/.config /var/www/.composer && chown -R www-data:www-data /var/www/.config /var/www/.composer

RUN composer global require laravel/installer

USER www-data

